# -*- coding: utf-8 -*-
"""Project_CNN_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vvgmqERgHiKKkuBS7cKiV9JvBi5JMVPc
"""

import pandas as pd
import numpy as np
from torchvision import datasets
import matplotlib.pyplot as plt
import seaborn as sns
import random
from sklearn.model_selection import train_test_split
from torch.utils.data import DataLoader, Dataset
import torch
import torch.nn as nn
from torch.utils.data import WeightedRandomSampler
from collections import Counter
from torchvision.transforms import transforms
from torchvision.models import efficientnet_b0, EfficientNet_B0_Weights
import torch.optim as optim
from PIL import Image
from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix

import os
from google.colab import drive
drive.mount('/content/drive')
!cp -r "/content/drive/MyDrive/HAM10000" "/content/"

print(len(os.listdir("/content/HAM10000/HAM10000_images_part_1")))
print(len(os.listdir("/content/HAM10000/HAM10000_images_part_2")))

df = pd.read_csv("/content/HAM10000/HAM10000_metadata.csv")

df.sample(5)

df.info()

sns.countplot(df['dx'])

df['dx'].value_counts()

X = []
y = []
label_map = {
    "nv": 0,
    "mel": 1,
    "bkl": 2,
    "bcc": 3,
    "akiec": 4,
    "vasc": 5,
    "df": 6
    }

for _, row in df.iterrows():

    image_id = row["image_id"]
    label = label_map[row["dx"]]

    X.append(image_id)
    y.append(label)

fig, axes = plt.subplots(5, 4, figsize=(8, 8))
fig.suptitle("20 Images", fontsize=16)

for i, ax in enumerate(axes.flat):

  idx = random.randint(0,10014)
  image_id, label = X[idx],y[idx]

  path1 = f"/content/HAM10000/HAM10000_images_part_1/{image_id}.jpg"
  path2 = f"/content/HAM10000/HAM10000_images_part_2/{image_id}.jpg"

  if os.path.exists(path1):
      img = Image.open(path1).convert("RGB")
  else:
      img = Image.open(path2).convert("RGB")

  ax.imshow(img)
  ax.set_title(f"Label: {label}")
  ax.axis("off")

plt.tight_layout(rect=[0, 0, 1, 0.98])
plt.show()

X_train, X_temp, y_train, y_temp = train_test_split(X,y,test_size=0.3,random_state=0,stratify=y)
X_test, X_val, y_test, y_val = train_test_split(X_temp,y_temp,test_size=0.5,random_state=0,stratify=y_temp)

custom_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]) # Added normalization
])

# Transform for displaying images (without normalization for Grad-CAM visualization)
display_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(), # Scales to [0, 1] and converts to FloatTensor
])

augment_transform = transforms.Compose([
     transforms.Resize((224, 224)),
     transforms.RandomHorizontalFlip(),
     transforms.RandomRotation(15),
     transforms.ColorJitter(brightness=0.2, contrast=0.2),
     transforms.RandomResizedCrop(224, scale=(0.85, 1.15)),
     transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
 ])

class CustomDataset(Dataset):

  def __init__(self, features, labels, transforms):

    self.features = features
    self.labels = labels
    self.transforms = transforms

    self.image_paths = []

    for image_id in features:

        path1 = f"/content/HAM10000/HAM10000_images_part_1/{image_id}.jpg"

        if os.path.exists(path1):
            self.image_paths.append(path1)
        else:
            self.image_paths.append(f"/content/HAM10000/HAM10000_images_part_2/{image_id}.jpg")

  def __len__(self):

    return len(self.features)

  def __getitem__(self, index):

    img = Image.open(self.image_paths[index]).convert("RGB")
    img = self.transforms(img)
    return img, torch.tensor(self.labels[index], dtype=torch.long)

class_counts = Counter(y_train)

sample_weights = [1.0 / class_counts[label] for label in y_train]

sampler = WeightedRandomSampler(
    weights=sample_weights,
    num_samples=len(sample_weights),
    replacement=True
)

train_dataset = CustomDataset(X_train, y_train, augment_transform)
test_dataset = CustomDataset(X_test, y_test, custom_transform)
val_dataset = CustomDataset(X_val, y_val, custom_transform)

train_loader = DataLoader(train_dataset, batch_size=32, sampler=sampler)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)
val_loader = DataLoader(val_dataset, batch_size=32, shuffle=False)

model = efficientnet_b0(weights=EfficientNet_B0_Weights.DEFAULT)

num_classes = 7

model.classifier[1] = nn.Linear(
    model.classifier[1].in_features,
    num_classes
)

# freezing model block and only training fc params
for param in model.parameters():
    param.requires_grad = False
for param in model.classifier.parameters():
    param.requires_grad = True

!pip install torchinfo
from torchinfo import summary

summary(model, input_size=(1, 3, 224, 224))

# model = model.to('cuda')
epochs1 = 10
lr1 = 0.001 # Reduced learning rate
criteria = nn.CrossEntropyLoss()
optimizer1 = optim.Adam(model.classifier.parameters(), lr=lr1, weight_decay=1e-4)

for epoch in range(epochs1):

    train_correct = 0
    train_total = 0

    total_epoch_loss = 0

    for batch_features, batch_labels in train_loader:

        batch_features = batch_features.to('cuda')
        batch_labels = batch_labels.to('cuda')

        outputs = model(batch_features)

        loss = criteria(outputs, batch_labels)

        optimizer1.zero_grad()
        loss.backward()
        optimizer1.step()

        total_epoch_loss += loss.item()
        _, predicted = torch.max(outputs, 1)

        train_total += batch_labels.size(0)
        train_correct += (predicted == batch_labels).sum().item()

    train_loss = total_epoch_loss / len(train_loader)
    train_acc = 100 * train_correct / train_total

    print(
        f"Epoch {epoch+1}/{epochs1} | "
        f"Train Loss: {train_loss:.4f} | "
        f"Train Acc: {train_acc:.2f}% | "
    )

for param in model.parameters():
    param.requires_grad = True
epochs2 = 20
lr2 = 1e-4 # Reduced learning rate
optimizer2 = optim.Adam(model.parameters(), lr=lr2, weight_decay=1e-4)

for epoch in range(epochs2):

    model.train()
    train_correct = 0
    train_total = 0

    total_epoch_loss = 0

    for batch_features, batch_labels in train_loader:

        batch_features = batch_features.to('cuda')
        batch_labels = batch_labels.to('cuda')

        outputs = model(batch_features)

        loss = criteria(outputs, batch_labels)

        optimizer2.zero_grad()
        loss.backward()
        optimizer2.step()

        total_epoch_loss += loss.item()
        _, predicted = torch.max(outputs, 1)

        train_total += batch_labels.size(0)
        train_correct += (predicted == batch_labels).sum().item()

    train_loss = total_epoch_loss / len(train_loader)
    train_acc = 100 * train_correct / train_total

    model.eval()

    val_loss = 0
    correct = 0
    total = 0

    with torch.no_grad():

        for batch_features, batch_labels in val_loader:

            batch_features = batch_features.to('cuda')
            batch_labels = batch_labels.to('cuda')

            outputs = model(batch_features)

            loss = criteria(outputs, batch_labels)

            val_loss += loss.item()

            _, predicted = torch.max(outputs, 1)

            total += batch_labels.size(0)
            correct += (predicted == batch_labels).sum().item()

    val_loss = val_loss / len(val_loader)
    val_acc = 100 * correct / total

    print(
        f"Epoch {epoch+1}/{epochs2} | "
        f"Train Loss: {train_loss:.4f} | "
        f"Val Loss: {val_loss:.4f} | "
        f"Train Acc: {train_acc:.2f}% | "
        f"Val Acc: {val_acc:.2f}%"
    )

model.eval()

# Train accuracy
total = 0
correct = 0

with torch.no_grad():
   for batch_features,batch_labels in train_loader:

    # Moving to GPU
    batch_features, batch_labels = batch_features.to('cuda'), batch_labels.to('cuda')

    outputs = model(batch_features)

    predicted = torch.max(outputs,1) # 1 signifies dimension

    total += batch_labels.shape[0]

    correct += (predicted.indices == batch_labels).sum().item()

print(correct/total)

y_true = []
y_pred = []

with torch.no_grad():
   for batch_features,batch_labels in test_loader:

    # Moving to GPU
    batch_features, batch_labels = batch_features.to('cuda'), batch_labels.to('cuda')

    outputs = model(batch_features)

    _,predicted = torch.max(outputs,1) # 1 signifies dimension

    y_true.extend(batch_labels.cpu().numpy())
    y_pred.extend(predicted.cpu().numpy())

# Model Verification metrics

acc = accuracy_score(y_true, y_pred)
macro_f1 = f1_score(y_true,y_pred,average='macro')

print(f"Test Accuracy: {acc*100:.2f}%")
print(f"Macro F1 Score: {macro_f1:.4f}")
print(classification_report(y_true,y_pred))

cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(8,6))

sns.heatmap(cm,annot=True,fmt='d',cmap='Blues')

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")

plt.show()

!pip install grad-cam

import cv2
import numpy as np
import matplotlib.pyplot as plt
import torch

from pytorch_grad_cam import GradCAM
from pytorch_grad_cam.utils.image import show_cam_on_image
from pytorch_grad_cam.utils.model_targets import ClassifierOutputTarget

target_layers = [model.features[-1][0]]

image_id = "ISIC_0025676"
image_path = f"/content/HAM10000/HAM10000_images_part_1/{image_id}.jpg"
img = Image.open(image_path).convert("RGB")

img_for_model = custom_transform(img) # This is the normalized image for the model
img_for_display = display_transform(img) # This is the image for display, in [0, 1] range

# Convert the image for display to numpy HWC format for show_cam_on_image
rgb_img = img_for_display.permute(1, 2, 0).numpy()

input_tensor = custom_transform(img).unsqueeze(0).to('cuda')

with torch.no_grad():
    output = model(input_tensor)
    pred_class = output.argmax(dim=1).item()

print("Predicted class:", pred_class)

cam = GradCAM(
    model=model,
    target_layers=target_layers
)

targets = [ClassifierOutputTarget(pred_class)]

grayscale_cam = cam(
    input_tensor=input_tensor,
    targets=targets
)[0]

visualization = show_cam_on_image(
    rgb_img,
    grayscale_cam,
    use_rgb=True
)

plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
plt.imshow(rgb_img)
plt.title(f"Original ({original_class_name})")
plt.axis("off")

plt.subplot(1,2,2)
plt.imshow(visualization)
plt.title(f"Grad-CAM (Predicted: {reverse_label_map[pred_class]})")
plt.axis("off")

plt.show()

